name = "electric-d1-sync"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB_NA"
database_name = "electric-sync-na"
database_id = "YOUR_NA_DATABASE_ID"

[[d1_databases]]
binding = "DB_EU"
database_name = "electric-sync-eu"
database_id = "YOUR_EU_DATABASE_ID"

[[d1_databases]]
binding = "DB_ASIA"
database_name = "electric-sync-asia"
database_id = "YOUR_ASIA_DATABASE_ID"

[[d1_databases]]
binding = "DB_SA"
database_name = "electric-sync-sa"
database_id = "YOUR_SA_DATABASE_ID"

[[d1_databases]]
binding = "DB_OC"
database_name = "electric-sync-oc"
database_id = "YOUR_OC_DATABASE_ID"

[[d1_databases]]
binding = "DB_AF"
database_name = "electric-sync-af"
database_id = "YOUR_AF_DATABASE_ID"

[vars]
ELECTRIC_URL = "http://localhost:3333/v1/shape"
WEBHOOK_SECRET = "your-secret-here"  # Add this to your environment variables
ELECTRIC_SOURCE_ID = ""
ELECTRIC_SOURCE_SECRET = ""

[triggers]
crons = ["* * * * *"]  # Run every minute
